# Generated by Django 5.1.6 on 2025-04-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
