# Generated by Django 5.2 on 2025-04-14 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='rental_date',
            new_name='order_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='rental_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
