# Generated by Django 5.2 on 2025-04-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('a', 'małe i mini'), ('b', 'miejskie'), ('c', 'kompaktowe'), ('d', 'rodzinne'), ('e', 'limuzyny'), ('f', 'luksusowe'), ('g', 'sportowe'), ('h', 'kabriolety'), ('i', 'terenowe'), ('m', 'van')], max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('description', models.TextField(default='Nowoczesne, komfortowe i niezawodne auto, idealne do codziennych podróży oraz długich tras.')),
                ('engine_type', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Benzyna'), ('Electric', 'Elektryczny'), ('Hybrid', 'Hybrydowy')], max_length=10)),
                ('engine_capacity', models.PositiveSmallIntegerField()),
                ('engine_power', models.PositiveSmallIntegerField()),
                ('gearbox', models.CharField(choices=[('Manual', 'Manualna'), ('Automatic', 'Automatyczna')], max_length=10)),
                ('fuel_consumption', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('doors_count', models.PositiveSmallIntegerField()),
                ('seats_count', models.PositiveSmallIntegerField()),
                ('body_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Convertible', 'Kabriolet'), ('Wagon', 'Kombi'), ('Van', 'Van'), ('Pickup', 'Pickup')], max_length=15)),
                ('year', models.PositiveSmallIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value', models.PositiveIntegerField()),
                ('mileage_limit', models.PositiveIntegerField()),
                ('equipment', models.ManyToManyField(to='cars.equipment')),
            ],
        ),
    ]
