# Generated by Django 5.2 on 2025-04-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
