# Generated by Django 5.2 on 2025-04-15 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cart_end_date_cart_start_date_cartitem_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='rental_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
