# Generated by Django 5.2 on 2025-04-16 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cartitem_car_alter_cart_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='birth_date',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
            preserve_default=False,
        ),
    ]
