# Generated by Django 5.2 on 2025-04-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_apartment_number_order_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
