# Generated by Django 5.2 on 2025-04-17 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_phone_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='cart',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
