# Generated by Django 5.2 on 2025-04-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_cart_end_date_alter_cart_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
