# Generated by Django 5.2 on 2025-04-17 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_cart_end_date_alter_cart_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cart',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
