# Generated by Django 5.2 on 2025-04-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_cart_end_date_alter_cart_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Zrealizowane'), ('in_progress', 'W trakcie'), ('not_completed', 'Niezrealizowane')], default='not_completed', max_length=20),
        ),
    ]
