# Generated by Django 5.2 on 2025-04-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_is_recommended'),
        ('orders', '0013_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car',
        ),
        migrations.AddField(
            model_name='order',
            name='cars',
            field=models.ManyToManyField(related_name='orders', to='cars.car'),
        ),
    ]
