# Generated by Django 5.2 on 2025-04-17 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_is_recommended'),
        ('orders', '0014_remove_order_car_order_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cars',
        ),
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cars.car'),
            preserve_default=False,
        ),
    ]
