# Generated by Django 5.2 on 2025-04-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], default=3),
            preserve_default=False,
        ),
    ]
