# Generated by Django 5.2 on 2025-04-19 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_average_rating'),
        ('orders', '0020_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_reviews', to='cars.car'),
        ),
    ]
