# Generated by Django 5.2 on 2025-05-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_review_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Karta kredytowa'), ('paypal', 'PayPal'), ('bank_transfer', 'Przelew bankowy'), ('cash_on_site', 'Gotowka przy odbiorze')], default='credit_card', max_length=20),
        ),
    ]
